version: '3'
services:
  patroni:
    image: postgres:9.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cola 
      POSTGRES_DB: development
    ports:
      - "5432:5432"
  web:
    build: .
    image: haryopramudito/opn-devops:patroni
    ports:
      - "3000:3000"
